### ISSUE TITLE
Specifying functions with multiple return values in WIT

### ISSUE THREAD

**Issue by calvinrp** [WebAssembly/component-model#103]
Forgive me if I missed docs/discussions on this one... It doesn't look like you are able to specify functions with multiple return values in WIT. Is this an intentional decision? Or a TODO? Or do you specify using tuple<>?

**Comment by lukewagner** [comment]
Yes, supporting multiple return values in Wit is indeed the intention and included in the current [WIT.md](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md#item-func) (now maintained in this repo).  Adding support for this to wit-bindgen is in-progress, iiuc.  Maybe @kulakowski-wasm can drop a link to the right issue?

**Comment by calvinrp** [comment]
Thank you for the clarification. I'd love to help out. Still trying to get familiar this code base.

**Comment by kulakowski-wasm** [comment]
Yes! This is tracked [here](https://github.com/bytecodealliance/wit-bindgen/issues/299) and I'm expecting this work to be wrapped up this week.

**Comment by lukewagner** [comment]
(Resolving this issue, since I think the root question is answered, but feel free to reopen if not.)
