### ISSUE TITLE
Is unit missing in the wit type list?

### ISSUE THREAD

**Issue by r12f** [WebAssembly/component-model#113]
I am seeing people using `unit` as return value in .wit files to represent "no return value", such as `()` in rust. However, I am not seeing unit defined in the wit format here: https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md. So I am wondering if I am missing anything or it is somehow missed in the format?

This is the current definition: https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md#types

```
ty ::= 'u8' | 'u16' | 'u32' | 'u64'
     | 's8' | 's16' | 's32' | 's64'
     | 'float32' | 'float64'
     | 'char'
     | 'bool'
     | 'string'
     | tuple
     | list
     | option
     | result
     | future
     | stream
     | id

tuple ::= 'tuple' '<' tuple-list '>'
tuple-list ::= ty
             | ty ',' tuple-list?

list ::= 'list' '<' ty '>'

option ::= 'option' '<' ty '>'

result ::= 'result' '<' ty ',' ty '>'
         | 'result' '<' '_' ',' ty '>'
         | 'result' '<' ty '>'
         | 'result'

future ::= 'future' '<' ty '>'
         | 'future'

stream ::= 'stream' '<' ty ',' ty '>'
         | 'stream' '<' '_' ',' ty '>'
         | 'stream' '<' ty '>'
         | 'stream'
```

And this is an example of usage: https://github.com/fermyon/spin/blob/7cbe44f32fcfb513940757ed6dc7e45e244ddab4/wit/ephemeral/outbound-redis.wit#L9

```rust
// Set key to value. If key alreads holds a value, it is overwritten.
set: func(address: string, key: string, value: payload) -> expected<unit, error>
```

**Comment by pchickey** [comment]
It was removed from the grammar here https://github.com/WebAssembly/component-model/pull/69. Spin is using a version of wit from before that change.

**Comment by alexcrichton** [comment]
Indeed this has been removed, so I'm going to close this. Hopefully the churn will settle down soon!

**Comment by r12f** [comment]
sounds great and thank you so much for the quick confirm!
