### ISSUE TITLE
Also define the canonical ABI in WebAssembly Text format

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/component-model#120]
I understand python is easier, but I can't imagine it being more precise than `%.wat` when discussing what something must be in WebAssembly.

ack some things are missing in wat, like switches, and also some things are harder to write or rely on larger functions. However, especially for signature and datatype mapping, wat is a better choice for WebAssembly than python, as at least it is a web standard and you can change it as necessary when finding out things don't work so well.

**Comment by lukewagner** [comment]
(Sorry for the delay; I was out.)  The Python code describes how to produce abstract (non-wasm) values out of wasm core values and linear memory, so it's not possible to use wat for this purpose.  Also, for some of the more involved lifting/lowering algorithms, the Python is considerably more concise and readable.  Ultimately, this Python is part of the informal spec that coordinates prototype implementation efforts ahead of a fully formal specification defined in the manner of the [core wasm spec](https://webassembly.github.io/spec/core/), as started in #101.  So the Python is not the final destination here.
