### ISSUE TITLE
Text "sugar" for aliases

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/component-model#13]
When reading the text format for a component recently I was struck with:

```wasm
(alias outer 1 0 (type (;0;)))
```

where with named indices would translate to:

```wasm
(alias outer $OUTER_COMPONENT $outer_name (type $local_name))
```

I originally found this somewhat confusing because there were a number of names and indices, and while we probably can't do much better for components without name sections I was wondering that sort of like how the core wasm text format allows:

```wasm
(func $f)
(export "f" (func $f))

;; ... is equivalent to ...

(func (export "f") $f)
```

could a simliar "inner" format be available for aliases:

```wasm
(alias outer 1 0 (type (;0;)))

;; ... would be equivalent to ...

(type (;0;) (alias outer 1 0))
```

or with names:

```wasm
(type $local_name (alias outer $OUTER_COMPONENT $outer_name))
```

where this mirrors how many definitions in the core text format are of the form `(item $items_name ...)`

**Comment by lukewagner** [comment]
Oops, yes, this was actually in the original module-linking explainer ([here](https://github.com/WebAssembly/module-linking/blob/main/design/proposals/module-linking/Explainer.md#alias-definitions), search "For symmetry with imports"), but I forgot to include it in the conversion to the component model.  I'll add it back.
