### ISSUE TITLE
Missing nonterminal definitions in the WIT EBNF

### ISSUE THREAD

**Issue by r-muhairi** [WebAssembly/component-model#152]
Hi,
whilst reading WIT's EBNF I noticed multiple missing nonterminal definitions, namely: `nil`, `strlit`, `id`

No, the [Identifier](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md#identifiers) section of the markdown does not constitute a nonterminal nor can act as one.

If there's reasoning behind any, I would love to know.
I'm not an expert of any kind in (E)BNF nor do I have experience writing an (E)BNF, so do feel free to correct me if I'm wrong.

Thank you

**Comment by lukewagner** [comment]
Thanks for filing.

`nil` is supposed to be the meta-linguistic symbol for the empty string, sometimes written ϵ.  Maybe we should replace it with ϵ?

#141 removes `strlit` as unused.

#141 documents more clearly that the definition of `id` in Wit is exactly the [`name`](https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md?plain=1#L203-L210) production in the component text format.

**Comment by r-muhairi** [comment]
> meta-linguistic symbol for the empty string,

`ϵ` sounds fine, however, we should probably add a "Note" alongside  per-say it to make it extra clear what this symbol refers to.

As #141 was merged, this is the only? undefined nonterminal as of now.
I'll open a PR if you're fine with ϵ symbol?

**Comment by lukewagner** [comment]
sgtm, thanks!
