### ISSUE TITLE
WIT.md grammatical production for `resource-item` not defined

### ISSUE THREAD

**Issue by esoterra** [WebAssembly/component-model#165]
No production rule or definition exists for the `resource-item` term.

**Comment by lukewagner** [comment]
Hah, yeah, it was added when there was prototype support in `wit-bindgen` and removed when that prototype support was removed in anticipation of the current proposed resources/handles.  It should be re-added fairly soon, but happy to remove the dangling reference in the interim.

**Comment by esoterra** [comment]
Resolved by #206
