### ISSUE TITLE
Why does convert_int_to_bool convert?

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/component-model#166]
The [Canonical ABI says](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#loading)

> Integer-to-boolean conversions treats 0 as false and all other bit-patterns as true

Why does it work this way, instead of doing `trap_if(i >= 2)` similar to what `i32_to_char` does?

(Aside: the names `convert_int_to_bool` and `i32_to_char` are a little inconsistent.)

[Rust](https://doc.rust-lang.org/reference/types/boolean.html) and many popular C and C++ ABIs use a convention of 0 meaning false and 1 meaning true, and could perform a no-op conversion of things like `list<bool>` into the source language if the Canonical ABI would guarantee that representation as well.

**Comment by lukewagner** [comment]
It's a good general question of whether to try to have the ABI trap as much as possible or, rather, check only what's necessary.  Initially, I had the rules try to trap as much as possible, but in a few [cases](https://github.com/WebAssembly/component-model/issues/34), this ended up rather complicating things so, to avoid being inconsistent, we [changed](https://github.com/WebAssembly/component-model/pull/35) our default to only trap when necessary.  Note that, while *lifting* allows the incoming value to be greater than `1`, *lowering* guarantees you a `0` or `1`, so I think you should have no-op conversions of `list<bool>` in both directions.

And yeah, I suppose `i32_to_char` should get a verb before it like all the other `verb_x_to_y` functions.  [Fixed](https://github.com/WebAssembly/component-model/commit/11d5b5e14d394205fdd264f2a39aa284e0941c89)

**Comment by sunfishcode** [comment]
The question has been answered!
