### ISSUE TITLE
waPC question

### ISSUE THREAD

**Issue by lperkov** [WebAssembly/component-model#168]
Is there any correlation between the upcoming component-model specification and the waPC (https://wapc.io/) project?

Would the upcoming component model specification be suitable to address the waPC use-cases as well?

Thanks!

**Comment by autodidaddict** [comment]
waPC isn't really a thing anymore tonky knowledge. wasmCloud is planning on embracing the component model as it becomes more of a stable thing that we can build on and utilize.

**Comment by lperkov** [comment]
Thank you for sharing and quick reply! That was my thinking as well but it was not as clear from the documentation.

Then just for my clarification and we can close the issue then - WASM Component Model will also provide the way for the WASM apps (guests) to call with the WASM host functions and vice versa at runtime?

**Comment by autodidaddict** [comment]
> Thank you for sharing and quick reply! That was my thinking as well but it was not as clear from the documentation.
> 
> Then just for my clarification and we can close the issue then - WASM Component Model will also provide the way for the WASM apps (guests) to call with the WASM host functions and vice versa at runtime?
> 

Yep! Today wasm provides a super basic means for guest and host interop, basically via numbers only. One promise of the component model is that we'll be able to model these interactions with wit and "worlds", and code generators will make it easier to cross the host/guest boundary via components than it is today for rich types.

**Comment by lperkov** [comment]
Thank you!
