### ISSUE TITLE
Static methods on resources don't have any validation on the resource name

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/component-model#182]
Currently I think this is a valid component:

```wasm
(component
  (import "[static]a.b" (func)))
```

since there's no validation about `[static]...` annotated-functions other than "it's a function". There could be no resources named `a`, though, in the component or there could be multiple (e.g. named through different paths through instances).

**Comment by lukewagner** [comment]
Oops, yes, thanks, that's missing from the validation rules.

**Comment by lukewagner** [comment]
I realized writing #190 that an above bullet (rewritten by #190) covers all the annotated name cases, thereby implying the above.

**Comment by lukewagner** [comment]
I think this is resolved, so closing, but feel free to reopen if not.
