### ISSUE TITLE
Should static methods and methods be allowed on nested resources?

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/component-model#183]
Currently I believe given the current validation rules this is a valid component:

```wasm
(component
  (import "i" (instance $i
    (export "t" (type (sub resource)))
  ))
  (alias export $i "t" (type $t))
  (import "[method]t.foo" (func (param "self" (borrow $t))))
)
```

Should this be valid, though? For example otherwise in a situation like:

```wasm
(component
  (import "i" (instance $i
    (export "t" (type (sub resource)))
  ))
  (import "i2" (instance $i2
    (export "t" (type (sub resource)))
  ))
  ;; ...
)
```

you can't import a method both for `$i.t` and `$i2.t` since they'd both be called `[method]t.foo`. 

Additionally retroactively adding methods/static methods to a type after its definition typically isn't allowed in many languages anyway, so should there perhaps be a validation predicate that if a `[method]` or a `[static]` is supplied that the mentioned resource is a top-level-import or top-level-export of the current component/instance wrapper? (this may relate a bit to https://github.com/WebAssembly/component-model/issues/182 in that case)

**Comment by lukewagner** [comment]
Yes, I think you're right; `[method]`s et al can only refer to resource exports in their current component def, component type or instance type, so the first example wouldn't validate either.  Furthermore, for component defs/types, I think imports can only refer to imports and exports could only refer to exports.
