### ISSUE TITLE
Clarifying where `borrow` is allowed

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/component-model#219]
Currently the `Binary.md` says:

> Validation only allows borrow to be used inside the param of a functype

This definitely allows `(param "self" (borrow $foo))`, but does it allow other things like:

```wasm
(param "x" (list (borrow $foo)))
```

or structural types:

```wasm
(type $t (record 
    (field "f" (borrow $foo))
))

(param "x" $t)
```

**Comment by lukewagner** [comment]
Good point, that's pretty fuzzy (in particular, since types are built up incrementally so that, at the point when you create a `(list (borrow $R))`, you don't yet know whether it will be used in a param, result, both or neither).
