### ISSUE TITLE
WIT.md resource-method func-item expansion results in double semi colon

### ISSUE THREAD

**Issue by patrickhuber** [WebAssembly/component-model#267]
Looking at the resource-method definition and func-item definition in the WIT.md, expanding the 'func-item' case results in the application of a double semi colon:

```
resource-method ::= func-item ';'
                  | id ':' 'static' func-type ';'
                  | 'constructor' param-list ';'

func-item ::= id ':' func-type ';'
```

I believe the resource-method definition should be changed to the following to avoid this as the func-item brings its own semi colon

```
resource-method ::= func-item
                  | id ':' 'static' func-type ';'
                  | 'constructor' param-list ';'

func-item ::= id ':' func-type ';'
```

**Comment by alexcrichton** [comment]
Thanks for spotting this! I've posted https://github.com/WebAssembly/component-model/pull/268 with the fix you suggested.

**Comment by lukewagner** [comment]
Good catch!
