### ISSUE TITLE
Comments/Questions

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/component-model#276]
I finally did an end-to-end read of all (well, most of) the docs in this repo. Since GH doesn't offer a means to comment on committed files, I created a dummy repo with a dummy PR of the entire content [here](https://github.com/rossberg/dummy/pull/1) and left my comments & questions there. Hope that indirection works well enough. :)

Overall, this looks great. I found the explainer particularly helpful and very well-written.

Happy to open individual issues for some of my comments/suggestions if they turn out to be relevant.

**Comment by lukewagner** [comment]
Awesome, thanks so much!  I'll definitely go through the comments and either turn them into PRs or ask questions here or open new issues, as appropriate.

**Comment by lukewagner** [comment]
Oops, this fell off my radar, but I started going through all the comments just now.  I started with a first pass that simply fixes typos in [this commit](https://github.com/WebAssembly/component-model/commit/4bafd0101b1a9fe3f6e8db520f3221259e8bb771).  For the rest, I'll submit some PRs so they can be reviewed.

**Comment by lukewagner** [comment]
Ok, I went through all the comments and either replied inline or folded the feedback into #339 or #341.  Happy to discuss more inline in those comment threads or on the above PRs or here.

**Comment by rossberg** [comment]
Thanks, I left a few more replies.

**Comment by lukewagner** [comment]
(Also filed #351.)

**Comment by lukewagner** [comment]
Ok, with #353 filed, I think I've gone through all the comments.  Thanks a lot for all the feedback and suggestions!

**Comment by lukewagner** [comment]
Great, thanks for filing #356 for discussion.  I'll close this issue b/c I think that's everything, but feel free to reopen if there's anything missing, or file new issues.
