### ISSUE TITLE
Is specifying a string encoding required?

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/component-model#30]
I stumbled across https://github.com/bytecodealliance/wasm-tools/issues/597 in our current work-in-progress implementation of the component model and it raised the question in this issue: when the `string` type is used in an API is it required that `canon.lift` and `canon.lower` specify an option indicating the encoding of the string? Or is the default specified if the option isn't otherwise encoded?

**Comment by lukewagner** [comment]
The current wording (in the paragraph after `canonopt` is defined in the Function Definitions section) is "If no string-encoding option is specified, the default is UTF-8. It is a validation error to include more than one string-encoding option.", so yes, it's fine to leave it off and there is a default.

**Comment by alexcrichton** [comment]
Ah ok thanks for the clarification, I was only looking at `Binary.md` and missed this clause.
