### ISSUE TITLE
i do not want component model

### ISSUE THREAD

**Issue by trcrsired** [WebAssembly/component-model#303]
I just need a VM that could run C and C++ and i do not want any web thing.

This entire thing is too hard to implement.

**Comment by sunfishcode** [comment]
It is a [foundational goal](https://github.com/WebAssembly/component-model/blob/main/design/high-level/Goals.md#component-model-high-level-goals) of the component model project here to avoiding biasing toward any one language or family of languages. These goals are shared by many people who participate in this project, so we're unlikely to make significant changes to them if it's just to serve one person's needs. If you have specific ideas for improving support for C or C++, within the context of these goals, we'd be interested in hearing them.

**Comment by trcrsired** [comment]
> It is a [foundational goal](https://github.com/WebAssembly/component-model/blob/main/design/high-level/Goals.md#component-model-high-level-goals) of the component model project here to avoiding biasing toward any one language or family of languages. These goals are shared by many people who participate in this project, so we're unlikely to make significant changes to them if it's just to serve one person's needs. If you have specific ideas for improving support for C or C++, within the context of these goals, we'd be interested in hearing them.

then you are biased against real hardware.
