### ISSUE TITLE
Minor issue in definiitons.py

### ISSUE THREAD

**Issue by GordonSmith** [WebAssembly/component-model#318]
Just looking at:  https://github.com/WebAssembly/component-model/blob/main/design/mvp/canonical-abi/definitions.py#L405-L406
```py
case Own()          : return lift_own(cx, load_int(cx.opts, ptr, 4), t)
case Borrow()       : return lift_borrow(cx, load_int(cx.opts, ptr, 4), t)
```

Looks like it should be:
```py
case Own()          : return lift_own(cx, load_int(cx, ptr, 4), t)
case Borrow()       : return lift_borrow(cx, load_int(cx, ptr, 4), t)
```

**Comment by lukewagner** [comment]
(Sorry for the slow reply) You're right; [fixed](https://github.com/WebAssembly/component-model/commit/eefe5459dce488707e0e01af7e8c10a35e886b33)

**Comment by lukewagner** [comment]
Also: thanks!
