### ISSUE TITLE
Possible issue with store_string_to_utf8

### ISSUE THREAD

**Issue by GordonSmith** [WebAssembly/component-model#327]
This is just from a visual inspection but https://github.com/WebAssembly/component-model/blob/main/design/mvp/canonical-abi/definitions.py#L695 looks like it may be incorrect?

```py
def store_string_to_utf8(cx, src, src_code_units, worst_case_size):
  assert(src_code_units <= MAX_STRING_BYTE_LENGTH)
  ptr = cx.opts.realloc(0, 0, 1, src_code_units)
  trap_if(ptr + src_code_units > len(cx.opts.memory))
  encoded = src.encode('utf-8')
  assert(src_code_units <= len(encoded))
  cx.opts.memory[ptr : ptr+src_code_units] = encoded[0 : src_code_units]
  if src_code_units < len(encoded):
    trap_if(worst_case_size > MAX_STRING_BYTE_LENGTH)
    ptr = cx.opts.realloc(ptr, src_code_units, 1, worst_case_size)
    trap_if(ptr + worst_case_size > len(cx.opts.memory))
    cx.opts.memory[ptr+src_code_units : ptr+len(encoded)] = encoded[src_code_units : ]    <----------------------------------------
    if worst_case_size > len(encoded):
      ptr = cx.opts.realloc(ptr, worst_case_size, 1, len(encoded))
      trap_if(ptr + len(encoded) > len(cx.opts.memory))
  return (ptr, len(encoded))
```

I think it should be:
```py
    cx.opts.memory[ptr : ptr+len(encoded)] = encoded[src_code_units : ]  
```

**Comment by lukewagner** [comment]
I might be missing your point, so tell me if that's the case, but I think the code is correct as it is because the `realloc` will preserve the contents of the original `memory[ptr : ptr+src_code_units]` copy and thus we only need to write the remainder of the bytes (starting at `ptr+src_code_units`).

**Comment by GordonSmith** [comment]
Unfortunately I believe that is not guaranteed in the c++ spec (but is commonly implemented that way) - but I have seen occasions when this is not true...

**Comment by GordonSmith** [comment]
You are corect - I  missed that you are only copying the truncated diff after the realloc!  Sorry for the noise.
