### ISSUE TITLE
ABI Assuming realloc to a smaller len will truncate existing alloc

### ISSUE THREAD

**Issue by GordonSmith** [WebAssembly/component-model#329]
This is not true for c++ guests (although it can be a common optimization in some clibs - but less likely on embedded systems etc.)

* https://github.com/WebAssembly/component-model/blob/main/design/mvp/canonical-abi/definitions.py#L697
* https://github.com/WebAssembly/component-model/blob/main/design/mvp/canonical-abi/definitions.py#L710
* https://github.com/WebAssembly/component-model/blob/main/design/mvp/canonical-abi/definitions.py#L738
* https://github.com/WebAssembly/component-model/blob/main/design/mvp/canonical-abi/definitions.py#L738
* https://github.com/WebAssembly/component-model/blob/main/design/mvp/canonical-abi/definitions.py#L738

**Comment by lukewagner** [comment]
I'm afraid I don't follow: `realloc()` is generally specified to preserve the original contents of the incoming buffer.  `realloc()` can of course return a different pointer than is passed as parameter (in which case the impl will have to copy over the original contents over to the returned buffer), but all 5 locations you linked to anticipate this by updating `ptr` with the return value of `cx.opts.realloc()`, so I don't see the problem.
