### ISSUE TITLE
Mistake in WIT Specification?

### ISSUE THREAD

**Issue by toadslop** [WebAssembly/component-model#342]
Hey all, I was reviewing the WIT specification and I noticed an inconsistency between how a Package Name is described in prose vs how it is specified and I wanted to confirm whether or not this is a mistake.

According to [the specification](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md#package-declaration), a package name (declaration?) should follow this pattern:

```
package-decl        ::= 'package' ( id ':' )+ id ( '/' id )* ('@' valid-semver)?  ';'
```

From this specification, the following package name should be valid:

```
package one:two:three:four/five/six/seven;
```

However, [this section](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md#package-names) specifies a more restricted format:

```md
All WIT packages are assigned a package name. Package names look like foo:bar@1.0.0 and have three fields:

- A namespace field, for example foo in foo:bar. This namespace is intended to disambiguate between registries, top-level organizations, etc. For example WASI interfaces use the wasi namespace.

- A package field, for example clocks in wasi:clocks. A "package" groups together a set of interfaces and worlds that would otherwise be named with a common prefix.

- An optional version field, specified as [full semver](https://semver.org/).
```

This description suggests that the specification should be:

```
package-decl        ::= 'package' id ':' id ('@' valid-semver)?  ';'
```

Could you clarify which is correct? I'll put in a PR for the fix once I get a response.

**Comment by alexcrichton** [comment]
Ah the format started out as `a:b@1.0.0`, but it was extended to support `a:b/c:d@1.0.0` and I think not necessarily all parts of the spec has caught up yet. This is one of the [gated features](https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md#gated-features) with the 🪺 emoji. Regardless it'd still be good to update!

**Comment by lukewagner** [comment]
Thanks, good catch; I'll update the prose to match the grammar (gated by 🪺).

**Comment by lukewagner** [comment]
Added [here](https://github.com/WebAssembly/component-model/commit/cc7bdbfa32c89056b9c974430eb0ae32655841ea)

**Comment by toadslop** [comment]
Thanks guys! I was wondering about that.
