### ISSUE TITLE
UnboundLocalError: cannot access local variable 'flat_vals' in lower_values

### ISSUE THREAD

**Issue by safx** [WebAssembly/component-model#375]
The function `lower_values` raises `UnboundLocalError` in some case.
```
    :
  File "/Users/mac/src/tmp/component-model/design/mvp/canonical-abi/definitions.py", line 1126, in lower_values
    return flat_vals
           ^^^^^^^^^
UnboundLocalError: cannot access local variable 'flat_vals' where it is not associated with a value
```

As an example, I fixed this problem and added unit tests to the commit https://github.com/safx/component-model/commit/797fea690aece18bf1c9d0d406bb91a0cd0a007d in the forked repository.

**Comment by lukewagner** [comment]
Thanks for pointing this out!  I fixed the typo and added a test [here](https://github.com/WebAssembly/component-model/commit/971d6492a4136e9050ae9b2a98c3de8615bc5629)
