### ISSUE TITLE
Is `importname'` rule has a typo?

### ISSUE THREAD

**Issue by dannypsnl** [WebAssembly/component-model#391]
In the binary format
```
importname' ::= 0x00 len:<u32> in:<importname>                       => in  (if len = |in|)
```
however, when I dump the binary I got `0x01`, is this a typo or version problem?

Tools version
- wasm-tools 1.216.0
- cargo-component-component 0.15.0

**Comment by alexcrichton** [comment]
Could you clarify what binary you're using and what you're seeing? Locally I see:

```
$ wasm-tools dump <<< "(component (import \"x\" (func)))"  
  0x0 | 00 61 73 6d | version 13 (Component)
      | 0d 00 01 00
  0x8 | 07 05       | component type section
  0xa | 01          | 1 count
  0xb | 40 00 01 00 | [type 0] Func(ComponentFuncType { params: [], results: Named([]) })
  0xf | 0a 06       | component import section
 0x11 | 01          | 1 count
 0x12 | 00 01 78 01 | [func 0] ComponentImport { name: ComponentImportName("x"), ty: Func(0) }
      | 00
```

where the import starts at 0x12. That has an 00 leading prefix, `01 78` is `"x"` and then `01 00` is "func index 0". Given all that it's expected that wasm-tools generates an 0x00 leading byte for imports.

**Comment by dannypsnl** [comment]
`src/lib.rs`
```rust
#[allow(warnings)]
mod bindings;

use bindings::Guest;

struct Component;

impl Guest for Component {
     fn add(x: i32, y: i32) -> i32 {
        x + y
    }
}

bindings::export!(Component with_types_in bindings);
```

In `Cargo.toml`:
```toml

```

**Comment by alexcrichton** [comment]
Ah thanks for clarifying! You've discovered a situation where wasm-tools was in a "halfway state" in transitioning from one format to another. I've opened https://github.com/bytecodealliance/wasm-tools/pull/1753 to fix this to always emit the 0x00 prefix byte. In that sense this bug is in wasm-tools, not the spec itself, and the spec as-written is correct.

**Comment by dannypsnl** [comment]
I see, thanks for clarifying.
