### ISSUE TITLE
Can records be empty?

### ISSUE THREAD

**Issue by ouillie** [WebAssembly/component-model#406]
According to the [current spec](https://github.com/WebAssembly/component-model/blob/3ed572fedabf2f78bd51f58a0376d5faf5d63b5a/design/mvp/WIT.md#item-record-bag-of-named-fields), they can't. But pretty much all the programming languages I know (Rust, Go, C++, Java, Python, Ruby, C [at least GCC]) allow you to define empty structs and/or classes. Sometimes it can be useful, such as for sentinel values. What if we allowed WIT records to be empty (no members)?

**Comment by tschneidereit** [comment]
Empty records used to be allowed, but [were changed to be disallowed](https://github.com/WebAssembly/component-model/pull/218) because there unfortunately are interop issues with them, as discussed in that PR.

For sentinel values I think a one-arm `enum` or `variant` could work?

**Comment by ouillie** [comment]
Ah, I swear I tried searching for existing discussions about this :) but didn't find that thread. Thanks for the tip.
