### ISSUE TITLE
(Re-)Consider multi-return vs unit

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/component-model#41]
In #29, we had an unresolved [comment thread](https://github.com/WebAssembly/component-model/pull/29#discussion_r870174315) about whether we should make component-level function results symmetric with parameters.  The question was independent (pre-existing) of #29, so that PR merged and this issue represents the continued discussion.

One interesting new technical argument just came up via @peterhuene's work: Component-level `start` sections calling functions that return "nothing" technically always return `unit`.  If we treated `unit` uniformly (pushed a new `unit` value into the value index space), then the "linearity" requirement (each value must be consumed exactly once) would mean we have to consume that `unit`... which would then produce a new `unit` (ad infinitum).  Thus, we have to special-case `unit` in the validation rules (so it doesn't push a value index) which is irregular and adds validation complexity.  It's not a massive problem, but it does add a point to the multi-return column (which can return an empty list of values).

**Comment by lukewagner** [comment]
#49 raises an interesting case where having an empty return (returning `undefined` to a JS caller) would produce a more-regular JS interface than a `unit`-return (returning `null` to a JS caller).

(I haven't forgotten about this issue; I just haven't had time to think and discuss more about it yet.)

**Comment by lukewagner** [comment]
Here's a third argument in favor of multi-return that I recently realized:

To support runtime instantiation of components (going beyond the declarative all-up-front instantiation we currently have), I've been imagining that we'd define a new canonical built-in `(canon instantiate $Component (func $new))` that defines a function `$new` that, when called, creates a new instance of `$Component`.  If `$Component` defines any function exports, then the return type of `$new` would be a `(handle $Component)` (with `$Component` serving as a resource type).  But if `$Component` exclusively exports values, then `$new` can simply be a normal function returning values (thereby realizing the [WASI "command" pattern](https://github.com/WebAssembly/WASI/issues/13)<sup>[1](https://docs.google.com/presentation/d/1MNVOZ8hdofO3tI0szg_i-Yoy0N2QPU2C--LzVuoGSlE/edit#slide=id.g13630a5e721_0_68)</sup>).  But now the asymmetry of parameters/results bites again: value import names can turn into parameter names but value export names must either be dropped or wrapped into a `record`.

**Comment by peterhuene** [comment]
I think the above makes a lot of sense to me. I don't have any objections with the other proposed changes.

Regarding option 2 from above:

> a param list is either all-named or contains a single unnamed type

Is my understanding of this, and the following paragraph you wrote, correct with the following summary?

```text
a param/result list is either empty, a single unnamed param/result, or all uniquely-named.

the empty string is considered a valid name.
```

If so, I think that option gives the most flexibility too.

**Comment by lukewagner** [comment]
Yep!  Thanks for clarifying.  Thus, you can write both `(func (result "" u32))` and `(func (result u32))` and they are (hopefully not too annoyingly in practice...) distinct types.

**Comment by lukewagner** [comment]
Writing this up, I realized we probably don't want to have `union` payloads be list of types: it makes the syntax way more awkward (lists of lists of types) and the point of `union` was to specialize anyways.  But other than that, everything described above is in #69.
