### ISSUE TITLE
Eager return from async-lifted/lowered functions

### ISSUE THREAD

**Issue by badeend** [WebAssembly/component-model#410]
Would it be beneficial to have a shortcut for cases where async functions are able to (conditionally) complete fully synchronously? Skipping as much of the subtask management whenever possible. I.e.

> Because the imported fetch function is canon lowered with async, its core function type takes pointers to the parameter and results (which are asynchronously read-from and written-to) and returns the index of a new subtask.

Can we add a sentinel return value (e.g. `0`) to indicate: "The core function managed to finish synchronously, no subtask has been created and the results have already been written. Good luck!"

AFAIK, the CM-runtime should be able to automagically deduce this when an async-lifted core callee returns, `task.return` has already been called and there are no remaining subtasks.

**Comment by lukewagner** [comment]
Yes, that is a good idea and indeed that is already the case :)  The place this appears is in [`canon_lower`](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#canon-lower) where `call_and_handle_blocking(do_call)` returns `Returned()` and then the lowered call returns `0` indicating to the caller that the outparams have already been written to.

**Comment by badeend** [comment]
Oh...

Well, problem solved!  :P
