### ISSUE TITLE
component model breaks protobuf main

### ISSUE THREAD

**Issue by SoniEx2** [WebAssembly/component-model#411]
protobuf main is a technique for passing typed, structured data over a stringly typed interface (argv): https://github.com/SoniEx2/protobuf-main/blob/default/sayhello/sayhello.c

unfortunately, thanks to component model, WASI 0.2 breaks protobuf main in two ways:

1. not allocating a single buffer for all argument strings
2. not allowing arbitrary bytes in argument strings

we'd appreciate if you could fix this back to how it was in WASI 0.1.

**Comment by sunfishcode** [comment]
That code invokes undefined behavior, on all platforms. A way to do what that code is doing without invoking undefined behavior is to allocate a new buffer and copy the argument strings into it.

**Comment by SoniEx2** [comment]
implementation-defined* but it works fine outside of wasm
