### ISSUE TITLE
Remove or note status of `refines`

### ISSUE THREAD

**Issue by lann** [WebAssembly/component-model#414]
The `refines` feature was removed from the explainer in #255 but is still referenced in the cabi docs. This has caused confusion for [at least one person](https://bytecodealliance.zulipchat.com/#narrow/channel/206238-general/topic/Small.20questions.20about.20WIT/near/482816027) so should probably either be completely removed or at least annotated with its current status.

**Comment by lukewagner** [comment]
Yes, agreed that that should have been ripped out earlier in #255; thanks for pointing it out!  Removed in [this commit](https://github.com/WebAssembly/component-model/commit/d7ca2f19adc6715477e0fac62c32f15c9873379c).
