### ISSUE TITLE
Rationale for using 32-bit WebIDL conversions for smaller integers

### ISSUE THREAD

**Issue by Liamolucko** [WebAssembly/component-model#48]
The explainer defines that integers smaller than 32 bits use `ToInt32`/`ToUint32` to convert from JS values:

> | Type | `ToJSValue` | `ToWebAssemblyValue` |
> | ---- | ----------- | -------------------- |
> | `s8`, `s16`, `s32` | as a Number value | `ToInt32` |
> | `u8`, `u16`, `u32` | as a Number value | `ToUint32` |

When I was looking at the spec for those, though, I noticed that the JS spec also defines [`ToInt16`](https://tc39.es/ecma262/#sec-toint16), [`ToUint16`](https://tc39.es/ecma262/#sec-touint16), [`ToInt8`](https://tc39.es/ecma262/#sec-toint8) and [`ToUint8`](https://tc39.es/ecma262/#sec-touint8). Is there any particular reason that the 32-bit versions are used instead of the dedicated 8- and 16-bit versions?

**Comment by lukewagner** [comment]
Ah, great point; no, that's just laziness I guess :)  Fixed in #52
