### ISSUE TITLE
Should `unit` map to `null` or `undefined`?

### ISSUE THREAD

**Issue by Liamolucko** [WebAssembly/component-model#49]
The explainer currently defines `unit` to map to `null` in JS. While attempting to implement that in `wit-bindgen` (which currently uses `undefined`), I realised that that would mean that functions with no return value (desugared to `unit`) would return `null` instead of `undefined`. That seems quite unnatural for JS, where a function with no return value gives a result of `undefined`. So, it might be a better idea for it to map to `undefined` instead.

#41 would also be a solution to that.

Aside from that one case, I don't have any preference for one over the other.

**Comment by Liamolucko** [comment]
A reason for `null`, though, is that lowering dictionary will throw a type error if a required field is `undefined`, without referencing the conversion for the particular type. That means that lowering a record with `undefined` for a `unit` field would fail (under the current definition of record lowering), which would be quite strange if `undefined` was what `unit`s mapped to in the other direction.

**Comment by lukewagner** [comment]
Right, your second comment is in the spirit of why `null` was chosen (as an intentional singular value vs. "not present").  But your first comment is a great reason why that is awkward and a nice supporting argument in favor of multi-return; I'll mention this in that issue.

**Comment by Liamolucko** [comment]
In lieu of multi-return, would it make sense to special case `unit` to map to `undefined` when used as a return value?
