### ISSUE TITLE
Copying a latin1 host string to latin1+utf16 encoding uses the wrong alignment

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/component-model#59]
Currently I think that this calls `store_string_copy` with a code unit size of 1 which becomes the alignment, but with https://github.com/WebAssembly/component-model/pull/54 and trying to have an alignment of 2 for all latin1+utf16 allocations I think this needs to be updated to have an alignment of 2 instead (perhaps another parameter to `store_string_copy` or similar)

**Comment by lukewagner** [comment]
Great point!  Technically our motivation in #54 doesn't apply here (we're not realloc'ing utf16 with the wrong alignment), but I think this is probably a good idea for 2 reasons:
* maybe the engine does a realloc (e.g., SM sometimes "inflates" latin1 to utf16)
* maybe it's useful to have the static invariant that latin1+utf16 strings are always 2-byte aligned
