### ISSUE TITLE
can `core:alias` have `outer`?

### ISSUE THREAD

**Issue by yamt** [WebAssembly/component-model#72]
reading https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md

i'm not sure if `core:alias` can have `outer` or not.

in some places, it seems saying it can't:

> There is no outer option in core:aliastarget because it would only be able to refer to enclosing core modules and module types and, until module-linking, modules and module types can't nest. In a module-linking future, outer aliases would be added, making core:alias symmetric to alias.

in other places, it seems saying otherwise:

> Lastly, the core:alias module declarator allows a module type definition to reuse (rather than redefine) type definitions in the enclosing component's core type index space via outer type alias. In the MVP, validation restricts core:alias module declarators to only allow outer type aliases but, in the future, more kinds of aliases would be meaningful and allowed.

**Comment by lukewagner** [comment]
Oops!  The first quoted text was originally true and then #44 added the latter text, but forgot to update the former (and Binary.md, which @peterhuene fixed in #46).  I'll fix shortly; thanks for reporting!
