### ISSUE TITLE
Clarifying zero-length strings/lists

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/component-model#78]
I was thinking more about [zero-sized array elements](https://github.com/WebAssembly/component-model/pull/77) in relation to zero-length strings and lists. The motivation for #77 is to avoid forcing checking the size of memory, but I think that the current specification is such that zero-length lists and strings must also force a check against the size of memory as specified.

* Lifting a string has the condition `trap_if(ptr + byte_length > len(opts.memory))` which would force a check against the size of memory in the case that `byte_length` is 0.
* Lifting a list has the condition `trap_if(ptr + length * size(elem_type) > len(opts.memory))` which would also force a check if `length` is 0.
* Lowering a string actually doesn't have any `trap_if(...)` conditions right now, which I think might be an oversight? 
* Lowering a list has the condition `trap_if(ptr + byte_length > len(opts.memory))` which is similar to lifting.

The original motivation for #77 came from eliding checks entirely in the case that fused adapters between wasm modules are themselves compiled to WebAssembly. While zero-size elements can have their length checks statically removed I don't think the check can be removed for the more common non-zero-sized elements in the case that the list length is zero.

Solving this issue could perhaps be done by moving the in-bounds-check to each iteration of the loop if the size of the element is bigger than zero. Solving this for strings though would be a bit trickier in the current spec code since the check would have to only trap if the byte length was bigger than 0.

**Comment by lukewagner** [comment]
You're right (and string lowering is indeed missing the `trap_if` -- I'll fix that in any case).  My impression was that: if it's natural to statically eliminate the loop, then we might as well eliminate the bounds check too, assuming this simplified the implementation (otherwise, we should keep the bounds check because `size(elem_type)=0` doesn't seem like a common case worth optimizing).  But for dynamic zero-length lists/strings, it seems like to avoiding checking `memory.length` would add an *extra* branch to detect the zero case which would mean *extra* work and so we shouldn't spec the branch elision.

**Comment by alexcrichton** [comment]
I was curious and refreshing my memory on `memory.copy` shows that [`memory.copy` does bounds checks](https://webassembly.github.io/spec/core/exec/instructions.html#xref-syntax-instructions-syntax-instr-memory-mathsf-memory-copy) even for zero-sized copies. Eventually ideally some of these copies like `(list u8)` are implemented via `memory.copy`, so if that's the case perhaps the bounds-check for zero-sized-types should stay in as well as keeping the current bounds checks even for zero-length arrays?

**Comment by lukewagner** [comment]
Yeah, writing the last comment that's what I was wondering as well.  If you're happy with that too, we can cancel #77.

**Comment by alexcrichton** [comment]
I think that's reasonable, yeah, and it means that the consequence is that bounds checks always must manually occur for lists/strings since the length can't ever proven to be nonzero.

**Comment by lukewagner** [comment]
Cool, done (and filed #81 to fix missing string lower traps)
