### ISSUE TITLE
Multiple `cabi_start` functions in Canonical ABI

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/component-model#88]
The component AST permits multiple `start` functions. Currently, the canonical ABI mangles them with the cabi version number and the signature, so if two start functions have the same signature, they'll mangle to the same thing. However, core wasm doesn't permit two exports to have the same name.

One option would be to add a sequence number to the mangling, like `cabi_start{sequence=0,cabi=0.1}: func()` or so. so that multiple start functions have distinct names, and canonicalABI consumers know what order to call them in.

**Comment by lukewagner** [comment]
While you're right that a component *definition* can contain multiple `start` definitions, the CABI is mangling a component *type*, which says nothing of `start` definitions; the `cabi_start` function is only derived from *value imports and exports* in the component type.  Thus, while it's still currently a [TODO](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#lifting-canonical-modules), `lift_canonical_module` would always only generate a single `start` definition in the lifted component definition.  (This is a consequence of the fact that the CABI cannot faithfully represent all expressible components, as noted in the final paragraph of [the CABI intro](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#canonical-abi).)

**Comment by sunfishcode** [comment]
Ah, I see it now. Thanks!
