### ISSUE TITLE
Can a function be lifted/lowered multiple times in sequence?

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/component-model#9]
Thinking about validation, I'm not sure what to do about a module that looks like:

```wasm
(component
  ;; ...
  (type $return_string (func (result string)))
  (instance $a (; ... ;))
  (instance $b (; ... ;))
  
  (func $lifted
    canon.lift $return_string (into $a) (func $a "return_string"))
  (func $lowered
    canon.lower (into $b) $lifted1)
  (func $lifted_again
    canon.lift $return_string (into $b) $lowered)
  
  (export "return_string" (func $lifted_again))
)
```

Here a function from `$a` is lifted but then immediately lowered again, only to be lifted again but this time with a different instance. As-is I believe that this module validates, but I don't know if it's supposed to validate or how it could be interpreted.

**Comment by peterhuene** [comment]
Is there a legitimate use case for relifting/relowering? Even if the `into` options were the same, I think, at best, that'd accomplish an aliasing (potentially at the cost of a naive runtime implementation creating unnecessary adapters sitting between the function calls).

If there isn't a use case, I think we should definitely prohibit this in validation.

**Comment by lukewagner** [comment]
You're right that, as currently written, nothing prevents these degenerate lift-then-lower pairs.  Previously, I had a vague intuition that, with a "fusion"/"link-time codegen" compilation model, these sorts of degenerate cases would Just Work.  But @peterhuene's point about aliasing is a really good one: once we have the [lockdown semantics](https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md#component-invariants) of the component model that prevent reentrance, in normal cross-instance cases, you can't observe the interleaved execution (or any post-trap state), which both makes the semantics simpler to reason about (lifting/lowering just do a big value-copy) and gives the generated code considerable room to optimally reorder loads/stores.  But if the source and destination linear-memories are the same, then all that is lost and we have to worry about precise interleavings (c.f. `memcpy` vs. `memmove`) which I don't think we should need to do to support this degenerate case.

So roughly, how about we make it an instantiation-time error if you have a `canon.lower` of a `canon.lift` with the same `memory`?  Actually, depending on precisely how it was specified, a trap might just naturally fall out of the lockdown semantics in these degenerate cases (it's reentrance!), but earlier seems better here.

**Comment by alexcrichton** [comment]
I don't have a use case for this myself, I'm trying to figure out what a runtime should do. For example should this be a validation error or an instantiation time error?

**Comment by lukewagner** [comment]
Making it a validation error is an interesting question.  So trying to think through what precisely the validation condition is: it's not fully sufficient to simply say "syntactically defined in the same component" since you can have fun `parent--{instantiate with}-->child--{re-export + alias}-->parent` cases.  It's also not the `memory` we care about so much as the component-instance (with the "lockdown state" bit).  This component-instance is closed over by the adapter function, so we'd need validation to track which symbolic component-instance an adapter function closes over which is maybe extra work for validation.  Now, for the purposes of link-time *compilation*, the optimizer is definitely tracking this component-instance information, so a valid compilation scheme is to emit `unreachable` (so it's a runtime error, not a validation error); possibly that's our simplest solution?

**Comment by alexcrichton** [comment]
Sorry I don't fully understand the `parent->child->parent` ascii you wrote down there, but one possible way to make this a validation error is `canon.lift` is restricted to not lifting an arbitrary function but rather:

```wasm
  (func $lifted
    canon.lift $return_string (into $a) "return_string")
```

where `canon.lift` requires the `into` option and the string payload is the export that's being lifted. This would avoid an otherwise-extraneous `alias` as well and otherwise I think would prevent these lifting/lowering chains which don't otherwise seem useful.

**Comment by lukewagner** [comment]
An expanded version of the ascii art is:
```wasm
(component
  (func $f (canon.lift ...))
  (component $Child
    (import "f1" (func $f))
    (export "f2" (func $f))
  )
  (instance $c (instantiate (component $Child) (with "f1" (func $f)))
  (alias export $c "f2" (func $f2))
  (func $g (canon.lower (func $f2)))
)
```
Here, `$g` lowers `$f`, which is in the same component, but the indirection through `$Child` makes it harder to see this in a simple syntactic way.

**Comment by lukewagner** [comment]
Incidentally, the dynamic trap does indeed fall out of the Canonical ABI, as described in the second-to-last paragraph [here](https://github.com/WebAssembly/component-model/blob/canonical-abi/design/mvp/CanonicalABI.md#canonlower).  My impression is that it's not worth it to try to define an earlier error which, to be complete in cases like I showed in the previous comment, would need to *spec* link-time flow analysis, so we're good with just the guaranteed trap.  Let me know if you all think differently or else we can close this issue when that PR merges.

**Comment by alexcrichton** [comment]
So it sounds like syntactically this is allowed and validates correctly, but the intention is that if you call the lifted version of a canon.lower'd function it always traps immediately?

Also, to confirm, the may enter/exit flag, that's at the component instance level, right?

**Comment by lukewagner** [comment]
Yes and yes

**Comment by alexcrichton** [comment]
Ok sounds good!

**Comment by alexcrichton** [comment]
Circling back to this now that I'm implementing this, I think given the currently spec'd Python, this will unconditionally trap:

```wasm
(component
  ;; First module/instance, a module that exports a function that returns the
  ;; empty string
  (module $a
    (memory (export "memory") 1)
    (func (export "canonical_abi_realloc") (param i32 i32 i32 i32) (result i32)
      i32.const 0)
    (func (export "canonical_abi_free") (param i32 i32 i32))

    (func (export "return-string") (result i32)
      (i32.store offset=0
        (i32.const 0)
        (i32.const 0))
      (i32.store offset=4
        (i32.const 0)
        (i32.const 0))
      i32.const 0)
  )
  (instance $a (instantiate (module $a)))

  ;; Lift the "return-string" from the above module to a component function
  (func $return_string_lift
    (canon.lift (func (result string)) (into $a) (func $a "return-string"))
  )

  ;; Define a "libc" to lower the $return_string_lift function into
  (module $b_libc
    (memory (export "memory") 1)
    (func (export "canonical_abi_realloc") (param i32 i32 i32 i32) (result i32)
      i32.const 0)
    (func (export "canonical_abi_free") (param i32 i32 i32))
  )
  (instance $b_libc (instantiate (module $b_libc)))

  ;; Lower our lifted function which will represents the copy from a's memory
  ;; into b's (or the b_libc memory)
  (func $return_string_lower
    (canon.lower (into $b_libc) (func $return_string_lift))
  )

  ;; Second module. This imports the "libc" memory and additionally imports the
  ;; function defined by the first module. This exports a single function which
  ;; calls the imported function
  (module $b
    (import "libc" "memory" (memory 1))
    (import "" "return-string" (func $return_string (param i32)))
    (func (export "entrypoint")
        (call $return_string (i32.const 8))
        (i32.load offset=4 (i32.const 8))
        i32.eqz
        br_if 0
        unreachable)
  )
  (instance $b (instantiate (module $b)
    (with "libc" (instance $b_libc))
    (with "" (instance (export "return-string" (func $return_string_lower))))
  ))

  ;; Lift the "entrypoint" from b to the outside world
  (func (export "entrypoint")
    (canon.lift (func) (into $b_libc) (func $b "entrypoint"))
  )
)
```

I'm specifically worried that the instance `$b` calls the python `canon_lower` which immediately sets `may_enter = False`, and then `canon_lift` will immediately trap with that value set.

This feels like it should be a valid use case of the component model? This could be "fixed" by introducing some component wrappers but I feel like the current `may_{enter,leave}` bits aren't in the best place. My hunch is that there's a better validation we can impose on lifting/lowering to allow situations like this but also disallow "weird" ones where you repeatedly lift and lower.

**Comment by alexcrichton** [comment]
Ok in talking with luke my [example above](https://github.com/WebAssembly/component-model/issues/9#issuecomment-1137880985) is indeed expected to trap, so no surprises there.

For the latter concern of mine he helped clarify how to interpret `canon.lower`'d functions and the compilation model for them. I think that will help ease my concerns but we didn't reach the conclusion that any spec changes should be made.

I'm actually going to go ahead and close this since my original question, in addition to the two recent concerns, have all been resolved.
